version: '2'
services:
  api:
    volumes:
      - "nfsmount:${CONTAINER_DIR}"

volumes:
  nfsmount:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      device: ":${SOURCE_DIR}"
